pipeline {
  agent any
    stages {
       stage('set environment') {
            steps {
                sh '/var/jenkins_home/env.sh'
            }
        }
        stage('Build') {
            steps {
                sh '/opt/apache-maven-3.8.8/bin/mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh '/opt/apache-maven-3.8.8/bin/mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
